apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-pulse-config
  namespace: cluster-pulse
data:
  redis_addr: "redis:6379"
  kafka_brokers: "kafka:9092"
  kafka_topic_name: "pod-events"
  groq_model: "llama-3.1-8b-instant"
  openai_model: "gpt-4o-mini"
  worker_concurrency_limit: "3"
  resource_snapshot_retention_days: "30"
  admin_username: "admin"